routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'HomeController@admin')->name('admin')->middleware(['role:admin']);


Route::resource('berita', 'BeritaController')->middleware('role:admin');

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $fillable = [
        'judul', 'kategori', 'konten','gambar','user_id'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BeritaController.php
<?php

namespace App\Http\Controllers;

use App\Berita;
use Illuminate\Http\Request;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $beritas = Berita::orderBy('id', 'desc')->paginate(10);
        return view('berita.index', compact('beritas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('berita.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|max:200',
            'konten'    => 'required|min:500',
            'kategori'  => 'required'
        ]);
        $request['user_id'] = Auth()->user()->id;
        $berita = Berita::create($request->except('gambar'));
        if($request->hasFile('gambar')){
           $berita->gambar =  $request->gambar->store('public');
           $berita->save();
        }
        return redirect()->route('berita.index')->with('status','Tambah Data berhasil');
        //dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $berita = Berita::find($id);
        return view('berita.show', compact('berita'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita = Berita::find($id);
        return view('berita.edit', compact('berita'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|max:200',
            'konten'    => 'required|min:500',
            'kategori'  => 'required'
        ]);
        $request['user_id'] = Auth()->user()->id;
        $berita = Berita::find($id);
        $berita->update($request->except('gambar'));
        if($request->hasFile('gambar')){
           $berita->gambar =  $request->gambar->store('public');
           $berita->save();
        }
        return redirect()->route('berita.index')->with('status','Ubah Data berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Berita  $berita
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        Berita::find($id)->delete();
        return redirect()->route('berita.index')->with('status','Hapus Data berhasil');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/berita/create.blade.php
@extends('layouts.app')

@section('content')
                <div class="card-header">Create Berita</div>

                <div class="card-body">
                    @if (count($errors) > 0)
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    {!! Form::model($berita = new App\Berita, ['url'=>route('berita.store'), 'files'=>'true']) !!}
                    
                    <div class="form-group">
                        {!! Form::label('judul', 'Judul Berita', []) !!}
                        {!! Form::text('judul', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('kategori', 'Kategori Berita', []) !!}
                        {!! Form::select('kategori', [
                            'Olahraga' => 'Olahraga',
                            'Politik' => 'Politik',
                            'Kesehatan' => 'Kesehatan',
                        ] , null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('gambar', 'Gambar Berita', []) !!}
                        {!! Form::file('gambar', ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('konten', 'Isi Berita', []) !!}
                        {!! Form::textarea('konten', null, ['class'=>'form-control']) !!}
                    </div>

                    {!! Form::submit('Simpan', ['class'=>'btn btn-danger ']) !!}

                    
                    {!! Form::close() !!}
                    
                </div>
@endsection

resources/views/berita/edit.blade.php
@extends('layouts.app')

@section('content')
                <div class="card-header">Create Berita</div>

                <div class="card-body">
                    @if (count($errors) > 0)
                        @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">
                            {{ $error }}
                        </div>
                        @endforeach
                    @endif
                    {!! Form::model($berita , ['url'=>route('berita.update', $berita->id), 'files'=>'true','method'=>'patch']) !!}
                    
                    <div class="form-group">
                        {!! Form::label('judul', 'Judul Berita', []) !!}
                        {!! Form::text('judul', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('kategori', 'Kategori Berita', []) !!}
                        {!! Form::select('kategori', [
                            'Olahraga' => 'Olahraga',
                            'Politik' => 'Politik',
                            'Kesehatan' => 'Kesehatan',
                        ] , null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('gambar', 'Gambar Berita', []) !!}
                        {!! Form::file('gambar', ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('konten', 'Isi Berita', []) !!}
                        {!! Form::textarea('konten', null, ['class'=>'form-control']) !!}
                    </div>

                    {!! Form::submit('Simpan', ['class'=>'btn btn-danger ']) !!}

                    
                    {!! Form::close() !!}
                    
                </div>
@endsection

resources/views/berita/index.blade.php
@extends('layouts.app')

@section('content')

                <div class="card-header">Berita <span class="float-right"> <a class="btn btn-outline-primary btn-sm" href="{{route('berita.create')}}"> Add </a> </span> </div>

                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>    
                                <th>Judul</th>    
                                <th>kategori</th>    
                                <th width="175">Aksi</th>    
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($beritas as $berita )
                            <tr>
                                <td>{{$berita->id}}</td>    
                                <td>{{$berita->judul}}</td>    
                                <td>{{$berita->kategori}}</td>    
                                <td>
                                    <a class="btn btn-outline-success btn-sm" href="{{route('berita.show', $berita->id)}}"> Show </a>
                                    <a class="btn btn-outline-warning btn-sm" href="{{route('berita.edit', $berita->id)}}"> Edit </a>
                                            
                                    {!! Form::open(['url'=>route('berita.destroy', $berita->id), 'class'=>'float-right', 'method'=>'delete']) !!}
                                    {!! Form::submit('Delete', ['class'=>'btn btn-outline-danger btn-sm']) !!}                        
                                    {!! Form::close() !!}
                                </td>    
                            </tr>
                            @empty
                            <tr>
                                <td colspan="4">Data masih kosong</td>        
                            </tr>
                            @endforelse

                        </tbody>
                    </table>
                    {{$beritas->links()}}
                </div>
@endsection

@push('script')
<script>
$('.btn-outline-danger').on('click',function(e){
e.preventDefault();
var form = $(this).parents('form');
swal({
  title: "Anda yakin?",
  text: "Once deleted, you will not be able to recover this data!",
  icon: "warning",
  buttons: true,
  dangerMode: true,
})
.then((willDelete) => {
  if (willDelete) {
    swal("Poof! Your data has been deleted!", {
      icon: "success",
    });
    form.submit();
  } 
});
});
</script>
@endpush

resources/views/berita/show.blade.php
@extends('layouts.app')

@section('content')

                <div class="card-body">
                        <li class="media">
                            <a class="d-flex" href="#">
                                <img src="{{Storage::url($berita->gambar)}}" alt="">
                            </a>
                            <div class="media-body">
                                <h5>{{$berita->judul}}</h5>
                                <h6>{{$berita->kategori}}</h6>
                                {{$berita->konten}}
                            </div>
                        </li>
                    
                </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->has('auth'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('auth') }}</strong>
                        </span>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
    .invalid-feedback {
        display: block!important; 
    }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li><a href="/berita">Berita</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        @if(session('status'))
                        <div class="alert alert-success" role="alert">
                            <strong>{{session('status')}}</strong>
                        </div>
                        @endif
                        <div class="card">
                        @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
@stack('script')
</html>